### ISSUE TITLE
Have these shipped? Can they be ordered?

### ISSUE THREAD

**Issue by DG12** [anabolyc/attiny-flasher#3]

**Comment by anabolyc** [comment]
All of the boards funded via Crowd Supply were delivered to Mouser, some of them not yet delivered to backers due to lack of the parts in the same order. 
Currently I cannot produce them due to the lack of ATMegax28 chips, but I have few boards left from the initial production run, They can be ordered at [Tindie](https://www.tindie.com/products/sonocotta/attiny-flasher/). 
I should update the README perhaps :)
